# Generated by Django 5.2.7 on 2025-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
